version: '3.9'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"  
    volumes:
      - ./postgre_data/:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/  
            
   


