-- Generated by the database client.
CREATE TABLE users(
    id SERIAL NOT NULL,
    login varchar(255) NOT NULL,
    password varchar(255),
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX users_login_key ON users USING btree ("login");
