-- Generated by the database client.
CREATE TABLE reg_expr(
    id SERIAL NOT NULL,
    request_id varchar(50) NOT NULL,
    reg_date timestamp without time zone NOT NULL,
    expression varchar(255) NOT NULL,
    result double precision DEFAULT 0.00,
    status varchar(50) NOT NULL DEFAULT 'new'::character varying,
    is_finished boolean NOT NULL DEFAULT false,
    finish_date timestamp without time zone,
    is_wrong boolean DEFAULT false,
    calc_duration integer NOT NULL DEFAULT 0,
    comment varchar(255),
    user_id integer NOT NULL,
    PRIMARY KEY(id)
);
CREATE INDEX idx_reg_expr_request_id ON reg_expr USING hash ("request_id");
COMMENT ON COLUMN reg_expr.request_id IS 'Идентификатор запроса на вычисление выражения';
COMMENT ON COLUMN reg_expr.reg_date IS 'Дата и время регистрации выражения на вычисление';
COMMENT ON COLUMN reg_expr.expression IS 'Выражение для вычисления';
COMMENT ON COLUMN reg_expr.result IS 'Результат вычисления выражения';
COMMENT ON COLUMN reg_expr.status IS 'Краткое описание: new, success, cancel, error';
COMMENT ON COLUMN reg_expr.is_finished IS 'Статус завершения вычисления выражения';
COMMENT ON COLUMN reg_expr.finish_date IS 'Дата и время завершения обработки вычисления';
COMMENT ON COLUMN reg_expr.is_wrong IS 'Флаг ошибки';
COMMENT ON COLUMN reg_expr.calc_duration IS 'Время обработки на вычислителе(в секундах)';
COMMENT ON COLUMN reg_expr.comment IS 'Комментарий';
