-- Generated by the database client.
CREATE TABLE calc_expr(
    id SERIAL NOT NULL,
    task_id bigint NOT NULL,
    create_date timestamp without time zone NOT NULL,
    expression varchar(255) NOT NULL,
    result double precision DEFAULT 0.00,
    is_finished boolean NOT NULL DEFAULT false,
    is_wrong boolean NOT NULL DEFAULT false,
    finish_date timestamp without time zone,
    rpn_expression varchar(255),
    comment varchar(255),
    "condition" integer NOT NULL DEFAULT 0,
    calc_daemon character(50),
    distrib_date timestamp without time zone,
    PRIMARY KEY(id)
);
COMMENT ON COLUMN calc_expr.task_id IS 'Идентификатор вычислительной задачи';
COMMENT ON COLUMN calc_expr.create_date IS 'Дата и время добавления в очередь  менеджера';
COMMENT ON COLUMN calc_expr.expression IS 'Выражение';
COMMENT ON COLUMN calc_expr.result IS 'Результат вычисления';
COMMENT ON COLUMN calc_expr.is_finished IS 'Флаг окончания обработки sub_expression';
COMMENT ON COLUMN calc_expr.is_wrong IS 'Флаг ошибки вычисления sub_expression';
COMMENT ON COLUMN calc_expr.finish_date IS 'Дата и время финализации';
COMMENT ON COLUMN calc_expr.rpn_expression IS 'Исходное выражение в нотации RPN';
COMMENT ON COLUMN calc_expr.comment IS 'Комментарий Менеджера-вычислителя';
COMMENT ON COLUMN calc_expr."condition" IS 'Состояние процесса вычисления';
COMMENT ON COLUMN calc_expr.distrib_date IS 'Дата и время назначения задания Демону';
